[package]
name = "trash-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.130", features = ["derive"] }
dirs-next = "2.0.0"
toml = "0.5.8"
humantime = "2.1.0"
